cmake/utils.cmake, include/geode/basic/common.h, include/geode/mesh/io/detail/geode_bitsery_mesh_input.h, include/geode/mesh/io/detail/geode_bitsery_mesh_output.h
More warnings is always better! ;)
=> build(Warning): Add pedantic warning level

cmake/utils.cmake
Ease development when used as a dependency.
=> fix(RPATH): Set RPATH relative to library path

include/geode/model/representation/builder/brep_builder.h, include/geode/model/representation/builder/section_builder.h, src/geode/model/representation/builder/brep_builder.cpp, src/geode/model/representation/builder/section_builder.cpp, tests/model/test-brep.cpp, tests/model/test-section.cpp, upgrade-guide.md
BREAKING CHANGE: some method signatures of BRepBuilder and SectionBuilder have changed.
fix #39
=> feat(Relationships): change name of methods adding a relationship between components by specifying the type of the relation

COPYLEFT, include/geode/basic/algorithm.h, include/geode/basic/factory.h, include/geode/basic/singleton.h, include/geode/geometry/bounding_box.h, src/geode/geometry/bounding_box.cpp, src/geode/mesh/builder/polyhedral_solid_builder.cpp, src/geode/mesh/core/polygonal_surface.cpp, src/geode/mesh/core/polyhedral_solid.cpp, src/geode/model/mixin/core/vertex_identifier.cpp, tests/basic/test-algorithm.cpp, tests/geometry/test-bounding-box.cpp, tests/mesh/test-polygonal-surface.cpp, tests/model/test-brep.cpp, tests/model/test-relationships.cpp, tests/model/test-section.cpp
@geologuic Are you ok with these modifications?
=> fix(Copyright): add clear mention of modified files from RINGMesh

include/geode/basic/attribute_manager.h, include/geode/basic/bitsery_archive.h, include/geode/basic/factory.h, include/geode/geometry/nn_search.h, include/geode/mesh/core/graph.h, include/geode/mesh/core/polygonal_surface.h, include/geode/mesh/core/polyhedral_solid.h, src/geode/basic/attribute_manager.cpp, src/geode/basic/zip_file.cpp, src/geode/geometry/nn_search.cpp, src/geode/mesh/builder/graph_builder.cpp, src/geode/mesh/core/bitsery_archive.cpp, src/geode/mesh/core/graph.cpp, src/geode/mesh/core/polygonal_surface.cpp, src/geode/mesh/core/polyhedral_solid.cpp, src/geode/model/mixin/core/relationships.cpp, tests/geometry/test-nnsearch.cpp
BREAKING CHANGE: replace std::vector by abseil containers when needed
=> perf(Container): improve container choice

include/geode/model/mixin/core/blocks.h, include/geode/model/mixin/core/corners.h, include/geode/model/mixin/core/lines.h, include/geode/model/mixin/core/model_boundaries.h, include/geode/model/mixin/core/relationships.h, include/geode/model/mixin/core/surfaces.h, include/geode/model/mixin/core/vertex_identifier.h, include/geode/model/representation/io/detail/geode_brep_output.h, include/geode/model/representation/io/detail/geode_section_output.h, src/geode/model/mixin/core/blocks.cpp, src/geode/model/mixin/core/corners.cpp, src/geode/model/mixin/core/lines.cpp, src/geode/model/mixin/core/model_boundaries.cpp, src/geode/model/mixin/core/relationships.cpp, src/geode/model/mixin/core/surfaces.cpp, src/geode/model/mixin/core/vertex_identifier.cpp
BREAKING CHANGE: remove useless string from save model methods
=> perf(Zip): simplify Brep and Section zip usage

include/geode/model/representation/core/section.h, src/geode/model/representation/core/section.cpp, tests/model/test-section.cpp
=> fix(Naming): homegeneize naming of embeddings

cmake/ConfigureBitsery.cmake
Going back to official bitsery repo. We need to apply a patch for old gcc 4.8
=> Bitsery patch

CMakeLists.txt, cmake/utils.cmake, tests/CMakeLists.txt
=> fix(CMake): fix environment settings for VS

include/geode/mesh/core/polygonal_surface.h, upgrade-guide.md
BREAKING CHANGE: implies modification of struct member edge_id
=> fix(PolygonsAroundVertex): use PolygonVertex instead of PolygonEdge

include/geode/mesh/core/regular_grid.h, src/geode/mesh/core/regular_grid.cpp, tests/mesh/test-regular-grid.cpp
This is a proposition to ease usage of the Grid. What do you think?
=> fix(RegularGrid): adjacency getters

cmake/ConfigureBitsery.cmake
Solve Visual Studio project generation (cc @mparquer)
=> fix(Bitsery): remove bitsery patch application

CMakeLists.txt, cmake/utils.cmake, tests/CMakeLists.txt, upgrade-guide.md
BREAKING CHANGE: CMake minimum requirement have been upgraded to 3.14
=> fix(PyPI): fix import module from Python

bindings/python/tests/model/test-py-brep.py, bindings/python/tests/model/test-py-convert-model-meshes.py, bindings/python/tests/model/test-py-section.py, include/geode/model/representation/io/brep_input.h, include/geode/model/representation/io/detail/geode_brep_input.h, include/geode/model/representation/io/detail/geode_section_input.h, include/geode/model/representation/io/section_input.h, src/bin/geode-triangulate-brep.cpp, src/bin/geode-triangulate-section.cpp, src/geode/model/representation/io/brep_input.cpp, src/geode/model/representation/io/section_input.cpp, tests/model/test-brep.cpp, tests/model/test-convert-model-meshes.cpp, tests/model/test-section.cpp
BREAKING CHANGE: parameters changed
=> fix(ModelInput): return the Model in the load_XX functions

include/geode/basic/permutation.h, include/geode/geometry/detail/aabb_impl.h, include/geode/geometry/morton.h, include/geode/mesh/builder/graph_builder.h, include/geode/mesh/builder/solid_mesh_builder.h, include/geode/mesh/builder/surface_mesh_builder.h, include/geode/mesh/builder/vertex_set_builder.h, src/geode/basic/permutation.cpp, src/geode/geometry/aabb.cpp, src/geode/geometry/morton.cpp, src/geode/mesh/builder/graph_builder.cpp, src/geode/mesh/builder/solid_mesh_builder.cpp, src/geode/mesh/builder/surface_mesh_builder.cpp, src/geode/mesh/builder/vertex_set_builder.cpp, tests/basic/test-permutation.cpp
BREAKING CHANGE: FixedArray was remove from some API in favor of std::vector
=> review-fiwedarray

include/geode/geometry/basic_objects.h, include/geode/mesh/core/surface_mesh.h, include/geode/model/mixin/builder/relationships_builder.h, include/geode/model/mixin/core/relationships.h, src/geode/model/mixin/builder/relationships_builder.cpp, src/geode/model/mixin/core/relationships.cpp
I also removed the deprecation since we are not really sure about the thresold value yet.
=> fix(Relation): remove relation

include/geode/geometry/basic_objects.h
=> fix(BasicObjects): add point setter

bindings/python/src/model/mixin/core/component_type.h, include/geode/basic/assert.h, include/geode/basic/logger.h, include/geode/mesh/core/solid_mesh.h, upgrade-guide.md
BREAKING change: type_name_static has been removed
fix #374
=> fix(SolidMesh): remove type_name_static method

bindings/python/src/geometry/bounding_box.h, include/geode/geometry/aabb.h, include/geode/geometry/bounding_box.h, include/geode/geometry/detail/aabb_impl.h, src/geode/geometry/aabb.cpp, src/geode/geometry/bounding_box.cpp
=> fix(AABBTree): refactoring

include/geode/mesh/io/detail/geode_bitsery_mesh_output.h, include/geode/mesh/io/edged_curve_output.h, include/geode/mesh/io/graph_output.h, include/geode/mesh/io/hybrid_solid_output.h, include/geode/mesh/io/io.h, include/geode/mesh/io/output.h, include/geode/mesh/io/point_set_output.h, include/geode/mesh/io/polygonal_surface_output.h, include/geode/mesh/io/polyhedral_solid_output.h, include/geode/mesh/io/regular_grid_output.h, include/geode/mesh/io/tetrahedral_solid_output.h, include/geode/mesh/io/triangulated_surface_output.h, include/geode/mesh/io/vertex_set_output.h, include/geode/model/representation/io/brep_output.h, include/geode/model/representation/io/detail/geode_brep_output.h, include/geode/model/representation/io/detail/geode_section_output.h, include/geode/model/representation/io/section_output.h, src/geode/mesh/io/edged_curve_output.cpp, src/geode/mesh/io/graph_output.cpp, src/geode/mesh/io/hybrid_solid_output.cpp, src/geode/mesh/io/point_set_output.cpp, src/geode/mesh/io/polygonal_surface_output.cpp, src/geode/mesh/io/polyhedral_solid_output.cpp, src/geode/mesh/io/regular_grid_output.cpp, src/geode/mesh/io/tetrahedral_solid_output.cpp, src/geode/mesh/io/triangulated_surface_output.cpp, src/geode/mesh/io/vertex_set_output.cpp, src/geode/model/representation/io/brep_output.cpp, src/geode/model/representation/io/section_output.cpp
BREAKING CHANGE: virtual method signature changed
=> fix(Output): take the object as parameter

bindings/python/src/mesh/core/solid_mesh.h, bindings/python/tests/mesh/test-py-polyhedral-solid.py, include/geode/mesh/core/solid_mesh.h, include/geode/model/helpers/component_mesh_polygons.h, src/geode/mesh/core/solid_mesh.cpp, src/geode/model/helpers/component_mesh_polygons.cpp, upgrade-guide.md
BREAKING CHANGE: PolyhedraAroundFacet content has changed
=> fix(SolidMesh): stor more information in the PolyhedraAroundFacet

src/geode/basic/CMakeLists.txt, src/geode/basic/uuid.cpp
libstdc++ can fail on parallel run
=> fix(UUID): switch to Abseil random generator

src/geode/mesh/io/edged_curve_input.cpp, src/geode/mesh/io/edged_curve_output.cpp, src/geode/mesh/io/graph_input.cpp, src/geode/mesh/io/graph_output.cpp, src/geode/mesh/io/hybrid_solid_input.cpp, src/geode/mesh/io/hybrid_solid_output.cpp, src/geode/mesh/io/point_set_input.cpp, src/geode/mesh/io/point_set_output.cpp, src/geode/mesh/io/polygonal_surface_input.cpp, src/geode/mesh/io/polygonal_surface_output.cpp, src/geode/mesh/io/polyhedral_solid_input.cpp, src/geode/mesh/io/polyhedral_solid_output.cpp, src/geode/mesh/io/regular_grid_input.cpp, src/geode/mesh/io/regular_grid_output.cpp, src/geode/mesh/io/tetrahedral_solid_input.cpp, src/geode/mesh/io/tetrahedral_solid_output.cpp, src/geode/mesh/io/triangulated_surface_input.cpp, src/geode/mesh/io/triangulated_surface_output.cpp, src/geode/mesh/io/vertex_set_input.cpp, src/geode/mesh/io/vertex_set_output.cpp, src/geode/model/representation/io/brep_input.cpp, src/geode/model/representation/io/brep_output.cpp, src/geode/model/representation/io/section_input.cpp, src/geode/model/representation/io/section_output.cpp
=> fix(IO): support EXTENSION by converting to lowercase

include/geode/basic/attribute.h, include/geode/geometry/point.h, src/geode/geometry/basic_objects/segment.cpp, src/geode/geometry/basic_objects/tetrahedron.cpp, src/geode/geometry/basic_objects/triangle.cpp, src/geode/geometry/distance.cpp, src/geode/mesh/core/geode_tetrahedral_solid.cpp, src/geode/mesh/core/grid.cpp
Where do you suggest to add ASSERTs?
=> perf(Container): prefer operator[] rather than method at

include/geode/model/helpers/detail/cut_along_internal_lines.h, include/geode/model/helpers/private/copy.h, include/geode/model/helpers/private/simplicial_model_creator.h, include/geode/model/representation/builder/detail/copy.h, include/geode/model/representation/core/brep.h, include/geode/model/representation/core/section.h, src/geode/model/helpers/convert_brep_section.cpp, src/geode/model/helpers/convert_model_meshes.cpp, src/geode/model/helpers/convert_to_mesh.cpp, src/geode/model/helpers/detail/cut_along_internal_lines.cpp, src/geode/model/helpers/model_component_filter.cpp, src/geode/model/helpers/simplicial_brep_creator.cpp, src/geode/model/helpers/simplicial_section_creator.cpp, src/geode/model/representation/builder/brep_builder.cpp, src/geode/model/representation/builder/section_builder.cpp
=> fix(Model): better handle template model dimension and builder

bindings/python/tests/geometry/test-py-distance.py, bindings/python/tests/geometry/test-py-point.py, bindings/python/tests/geometry/test-py-points_sort.py, bindings/python/tests/geometry/test-py-rotation.py, bindings/python/tests/mesh/test-py-edged-curve.py, bindings/python/tests/mesh/test-py-geometrical-opeations-on-mesh.py, bindings/python/tests/model/test-py-component-mesh-polygons.py, examples/layer_cake.ipynb, include/geode/geometry/point.h, src/geode/geometry/basic_objects/triangle.cpp, src/geode/geometry/distance.cpp, tests/geometry/test-distance.cpp, tests/geometry/test-point.cpp, tests/geometry/test-projection.cpp, tests/geometry/test-rotation.cpp, tests/mesh/test-aabb-triangulated-surface-helpers.cpp, tests/mesh/test-edged-curve.cpp, tests/mesh/test-geometrical-operations-on-mesh.cpp, tests/mesh/test-regular-grid-function.cpp, tests/mesh/test-tetrahedral-solid-function.cpp, tests/mesh/test-triangulated-surface-function.cpp, tests/model/test-component-mesh-polygons.cpp, upgrade-guide.md
=> fix(Point): remove epsilon parameter from inexact_equal

bindings/python/src/mesh/helpers/convert_surface_mesh.h, include/geode/mesh/helpers/convert_surface_mesh.h, src/geode/mesh/helpers/convert_surface_mesh.cpp, upgrade-guide.md
=> fix(MeshHelpers): uniformize merge functions API

include/geode/geometry/aabb.h, include/geode/geometry/detail/aabb_impl.h, include/geode/mesh/helpers/ray_tracing.h, src/geode/mesh/helpers/ray_tracing.cpp, tests/geometry/test-aabb.cpp, upgrade-guide.md
BREAKING CHANGE: intersection functors now returns a boolean
=> fix(AABB): stop intersection search asap

include/geode/mesh/helpers/convert_edged_curve.h, include/geode/mesh/helpers/convert_point_set.h, include/geode/mesh/helpers/convert_surface_mesh.h, include/geode/mesh/helpers/private/copy.h, include/geode/model/helpers/convert_brep_section.h, src/geode/mesh/helpers/convert_edged_curve.cpp, src/geode/mesh/helpers/convert_point_set.cpp, src/geode/mesh/helpers/convert_surface_mesh.cpp, src/geode/model/helpers/convert_brep_section.cpp, tests/mesh/test-convert-surface.cpp, tests/model/test-convert-brep.cpp, upgrade-guide.md
BREAKING CHANGE:
feat(2d to 3d converters): add a parameter.
Now, you can choose the value of the coordinate to add.
=> 2D to 3D converter

include/geode/mesh/core/attribute_coordinate_reference_system.h, include/geode/mesh/core/point_set.h, src/geode/mesh/core/attribute_coordinate_reference_system.cpp, src/geode/mesh/core/bitsery_archive.cpp, src/geode/mesh/core/edged_curve.cpp, src/geode/mesh/core/point_set.cpp, src/geode/mesh/core/solid_mesh.cpp, src/geode/mesh/core/surface_mesh.cpp, tests/mesh/test-edged-curve.cpp, tests/mesh/test-point-set.cpp, tests/mesh/test-polygonal-surface.cpp, tests/mesh/test-polyhedral-solid.cpp, tests/mesh/test-tetrahedral-solid.cpp, tests/mesh/test-triangulated-surface.cpp, tests/model/test-brep.cpp, tests/model/test-section.cpp
=> fix(CRS): missing cll to move constructor

cmake/utils.cmake
Proposition: a new target `test-wheel` to install and import a generated wheel
I will change the workflows once merged
=> Test import wheel

include/geode/mesh/core/private/grid_impl.h, include/geode/model/representation/builder/detail/copy.h, src/geode/mesh/helpers/euclidean_distance_transform.cpp, src/geode/model/helpers/aabb_model_helpers.cpp, src/geode/model/helpers/detail/cut_along_internal_lines.cpp, src/geode/model/helpers/detail/cut_along_internal_surfaces.cpp, src/geode/model/mixin/core/blocks.cpp, src/geode/model/mixin/core/corners.cpp, src/geode/model/mixin/core/lines.cpp, src/geode/model/mixin/core/surfaces.cpp, tests/basic/test-assert.cpp
New function: when_all_ref() to call when using reference_wrapper
https://github.com/Geode-solutions/asyncplusplus/commit/d4076a8e97232e743da453b740b404db129cab1c
=> fix(Async++): new fork to handle reference_wrapper

include/geode/geometry/barycentric_coordinates.h, src/geode/geometry/barycentric_coordinates.cpp, src/geode/geometry/intersection.cpp
=> Noexcept barycentric coordinates

cmake/CppTargets.cmake
It works on @BenPinet computer
ex: ninja run-my-exe
=> fix(CMake): add script to run executables

include/geode/geometry/point.h
What do you think about returning geometric info at the location of the exception?
=> feat(Exception): add new exception

include/geode/basic/types.h
=> fix(Types): missing include

include/geode/geometry/position.h, src/geode/geometry/position.cpp, src/geode/mesh/helpers/rasterize.cpp
=> fix(Rasterize): better management of limit case in 2d projection for close surface rasterization

include/geode/geometry/aabb.h, include/geode/geometry/detail/aabb_impl.h, include/geode/mesh/helpers/aabb_edged_curve_helpers.h, include/geode/mesh/helpers/aabb_solid_helpers.h, include/geode/mesh/helpers/aabb_surface_helpers.h, src/geode/mesh/helpers/aabb_edged_curve_helpers.cpp, src/geode/mesh/helpers/aabb_solid_helpers.cpp, src/geode/mesh/helpers/aabb_surface_helpers.cpp, src/geode/mesh/helpers/hausdorff_distance.cpp, tests/geometry/test-aabb.cpp, tests/mesh/test-aabb-edged-curve-helpers.cpp, tests/mesh/test-aabb-tetrahedral-solid-helpers.cpp, tests/mesh/test-aabb-triangulated-surface-helpers.cpp
BREAKING CHANGE: the return type of AABBTree::closest_element_box changed by losing the point
=> perf(AABB): return only the distance from the closest_element query

bindings/python/src/mesh/helpers/rasterize.cpp, include/geode/mesh/helpers/rasterize.h, src/geode/mesh/helpers/rasterize.cpp, tests/mesh/test-rasterize.cpp
BREAKING CHANGE: renamed rasterize_triangle in conservative_rasterize_triangle
=> fix(Rasterize): new name conservative_rasterize_triangle
